/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiImagesRouteImport } from './routes/api/images'
import { Route as AuthenticatedPromptsNewRouteImport } from './routes/_authenticated/prompts/new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesRoute = ApiImagesRouteImport.update({
  id: '/api/images',
  path: '/api/images',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPromptsNewRoute = AuthenticatedPromptsNewRouteImport.update({
  id: '/prompts/new',
  path: '/prompts/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/api/images': typeof ApiImagesRoute
  '/prompts/new': typeof AuthenticatedPromptsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/api/images': typeof ApiImagesRoute
  '/prompts/new': typeof AuthenticatedPromptsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/api/images': typeof ApiImagesRoute
  '/_authenticated/prompts/new': typeof AuthenticatedPromptsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gallery' | '/login' | '/api/images' | '/prompts/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gallery' | '/login' | '/api/images' | '/prompts/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/gallery'
    | '/login'
    | '/api/images'
    | '/_authenticated/prompts/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  ApiImagesRoute: typeof ApiImagesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images': {
      id: '/api/images'
      path: '/api/images'
      fullPath: '/api/images'
      preLoaderRoute: typeof ApiImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/prompts/new': {
      id: '/_authenticated/prompts/new'
      path: '/prompts/new'
      fullPath: '/prompts/new'
      preLoaderRoute: typeof AuthenticatedPromptsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPromptsNewRoute: typeof AuthenticatedPromptsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPromptsNewRoute: AuthenticatedPromptsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  ApiImagesRoute: ApiImagesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
