/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryIdRouteImport } from './routes/gallery_.$id'
import { Route as ApiImagesRouteImport } from './routes/api/images'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminPromptsIndexRouteImport } from './routes/_authenticated/admin/prompts/index'
import { Route as AuthenticatedAdminPromptsNewRouteImport } from './routes/_authenticated/admin/prompts/new'
import { Route as AuthenticatedAdminPromptsIdEditRouteImport } from './routes/_authenticated/admin/prompts/$id/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIdRoute = GalleryIdRouteImport.update({
  id: '/gallery_/$id',
  path: '/gallery/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesRoute = ApiImagesRouteImport.update({
  id: '/api/images',
  path: '/api/images',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPromptsIndexRoute =
  AuthenticatedAdminPromptsIndexRouteImport.update({
    id: '/prompts/',
    path: '/prompts/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromptsNewRoute =
  AuthenticatedAdminPromptsNewRouteImport.update({
    id: '/prompts/new',
    path: '/prompts/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromptsIdEditRoute =
  AuthenticatedAdminPromptsIdEditRouteImport.update({
    id: '/prompts/$id/edit',
    path: '/prompts/$id/edit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/images': typeof ApiImagesRoute
  '/gallery/$id': typeof GalleryIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/prompts/new': typeof AuthenticatedAdminPromptsNewRoute
  '/admin/prompts/': typeof AuthenticatedAdminPromptsIndexRoute
  '/admin/prompts/$id/edit': typeof AuthenticatedAdminPromptsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/api/images': typeof ApiImagesRoute
  '/gallery/$id': typeof GalleryIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/prompts/new': typeof AuthenticatedAdminPromptsNewRoute
  '/admin/prompts': typeof AuthenticatedAdminPromptsIndexRoute
  '/admin/prompts/$id/edit': typeof AuthenticatedAdminPromptsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/api/images': typeof ApiImagesRoute
  '/gallery_/$id': typeof GalleryIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/prompts/new': typeof AuthenticatedAdminPromptsNewRoute
  '/_authenticated/admin/prompts/': typeof AuthenticatedAdminPromptsIndexRoute
  '/_authenticated/admin/prompts/$id/edit': typeof AuthenticatedAdminPromptsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/login'
    | '/admin'
    | '/api/images'
    | '/gallery/$id'
    | '/admin/'
    | '/admin/prompts/new'
    | '/admin/prompts/'
    | '/admin/prompts/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/login'
    | '/api/images'
    | '/gallery/$id'
    | '/admin'
    | '/admin/prompts/new'
    | '/admin/prompts'
    | '/admin/prompts/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/gallery'
    | '/login'
    | '/_authenticated/admin'
    | '/api/images'
    | '/gallery_/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/prompts/new'
    | '/_authenticated/admin/prompts/'
    | '/_authenticated/admin/prompts/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  ApiImagesRoute: typeof ApiImagesRoute
  GalleryIdRoute: typeof GalleryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery_/$id': {
      id: '/gallery_/$id'
      path: '/gallery/$id'
      fullPath: '/gallery/$id'
      preLoaderRoute: typeof GalleryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images': {
      id: '/api/images'
      path: '/api/images'
      fullPath: '/api/images'
      preLoaderRoute: typeof ApiImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/prompts/': {
      id: '/_authenticated/admin/prompts/'
      path: '/prompts'
      fullPath: '/admin/prompts/'
      preLoaderRoute: typeof AuthenticatedAdminPromptsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/prompts/new': {
      id: '/_authenticated/admin/prompts/new'
      path: '/prompts/new'
      fullPath: '/admin/prompts/new'
      preLoaderRoute: typeof AuthenticatedAdminPromptsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/prompts/$id/edit': {
      id: '/_authenticated/admin/prompts/$id/edit'
      path: '/prompts/$id/edit'
      fullPath: '/admin/prompts/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminPromptsIdEditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPromptsNewRoute: typeof AuthenticatedAdminPromptsNewRoute
  AuthenticatedAdminPromptsIndexRoute: typeof AuthenticatedAdminPromptsIndexRoute
  AuthenticatedAdminPromptsIdEditRoute: typeof AuthenticatedAdminPromptsIdEditRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPromptsNewRoute: AuthenticatedAdminPromptsNewRoute,
  AuthenticatedAdminPromptsIndexRoute: AuthenticatedAdminPromptsIndexRoute,
  AuthenticatedAdminPromptsIdEditRoute: AuthenticatedAdminPromptsIdEditRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  ApiImagesRoute: ApiImagesRoute,
  GalleryIdRoute: GalleryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
